# ML-based Novelty Detection and Classification of Security Threats in IoT Networks

Disclaimer: this is a reduced (faster) version of the experiments presented in the paper.

#### Importing libraries

In [1]:
import warnings
from numba.core.errors import NumbaDeprecationWarning, NumbaPendingDeprecationWarning
warnings.simplefilter('ignore', category=NumbaDeprecationWarning)
warnings.simplefilter('ignore', category=NumbaPendingDeprecationWarning)

In [2]:
import json
import random
from datetime import datetime

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import optuna
import pandas as pd
import psutil
from featurewiz import FeatureWiz
from imblearn.combine import SMOTETomek
from lightgbm import LGBMClassifier
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.kernel_approximation import Nystroem
from sklearn.linear_model import SGDOneClassSVM
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import LocalOutlierFactor
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

Imported 0.3.1 version. Select nrows to a small number when running on huge datasets.
output = featurewiz(dataname, target, corr_limit=0.90, verbose=2, sep=',',
		header=0, test_data='',feature_engg='', category_encoders='',
		dask_xgboost_flag=False, nrows=None, skip_sulov=False)
Create new features via 'feature_engg' flag : ['interactions','groupby','target']

# Constants, RNG setup and utils

In [4]:
CFG_FRACTION = 0.01
CFG_SCENARIO = 'Scan'
CFG_SEED = 42
CFG_N_JOBS = int(np.sqrt(psutil.cpu_count(logical=False)))
CFG_N_TRIALS = 20

In [5]:
np.random.seed(CFG_SEED)
np.random.rand(CFG_SEED)
random.seed(CFG_SEED)

In [6]:
# Filter trials (i.e. remove trials that were pruned)
def filter_completed_trials(trials):
    completed_trials = [x for x in trials if x.state == optuna.trial.TrialState.COMPLETE]
    return completed_trials

In [7]:
# Get total execution time in seconds
def get_time(trial):
    start, end = trial.datetime_start, trial.datetime_complete
    return (end - start).total_seconds()

In [8]:
# Compute statistics for the results
def get_results_statistics(study):
    completed_trials = filter_completed_trials(study.trials)
    return {
        'score_min': np.min([x.values for x in completed_trials]),
        'score_max': np.max([x.values for x in completed_trials]),
        'score_mean': np.mean([x.values for x in completed_trials]),
        'score_std': np.std([x.values for x in completed_trials]),
        'time_min' : np.min([get_time(x) for x in completed_trials]),
        'time_max' : np.min([get_time(x) for x in completed_trials]),
        'time_mean' : np.mean([get_time(x) for x in completed_trials]),
        'time_std' : np.std([get_time(x) for x in completed_trials])
    }

In [9]:
# Print value counts with count and frequency
def pretty_print_value_counts(df, column=None):
    if column:
        c = df[column].value_counts(dropna=False)
        p = df[column].value_counts(dropna=False, normalize=True).mul(100).round(1).astype(str) + '%'
    else:
        c = df.value_counts(dropna=False)
        p = df.value_counts(dropna=False, normalize=True).mul(100).round(1).astype(str) + '%'
    print(pd.concat([c,p], axis=1, keys=['counts', '%']))

# Data Preprocessing

#### Reading dataset

In [10]:
# Read the dataset
df = pd.read_parquet('IoT_Network_Intrusion_Macro.parquet').sample(frac=CFG_FRACTION, random_state=CFG_SEED)

# Irrelevant features for training
df = df.drop(['ip.src', 'ip.dst'], axis=1) 

# Target feature
target = 'label'
df[target].replace('DenialofServiceDoS', 'DoS', inplace=True)
df[target].replace('ManintheMiddleMITM', 'MITM', inplace=True)
df[target].replace('MiraiBotnet', 'Mirai', inplace=True)
df[target].replace('Scanning', 'Scan', inplace=True)

#### Showing all target labels (categories)

In [11]:
pretty_print_value_counts(df, target)

        counts      %
label
Normal   14464  54.4%
Mirai    10206  38.4%
MITM       996   3.7%
DoS        682   2.6%
Scan       235   0.9%

#### Converting categories into numeric values

In [12]:
df[target], categories = pd.factorize(df[target], sort=False)
reverse_mappings = {i:categories[i] for i in range(len(categories.values))}

In [13]:
reverse_mappings

{0: 'Normal', 1: 'Mirai', 2: 'MITM', 3: 'DoS', 4: 'Scan'}

In [14]:
pretty_print_value_counts(df, target)

       counts      %
label
0       14464  54.4%
1       10206  38.4%
2         996   3.7%
3         682   2.6%
4         235   0.9%

In [15]:
outlier_labels = [CFG_SCENARIO]
outlier_indices = [k for k,v in reverse_mappings.items() if v in outlier_labels]
outlier_rows = df[target].isin(outlier_indices)
inlier_rows = ~df[target].isin(outlier_indices)

# Feature Selection

In [16]:
X = df.drop([target], axis=1)
y = df[target]

fwiz = FeatureWiz(corr_limit=0.80, verbose=0).fit(X, y)

fwiz.features

wiz = FeatureWiz(verbose=1)
        X_train_selected = wiz.fit_transform(X_train, y_train)
        X_test_selected = wiz.transform(X_test)
        wiz.features  ### provides a list of selected features ###

featurewiz has selected 0.8 as the correlation limit. Change this limit to fit your needs...
Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
#### Single_Label Multi_Classification problem ####
    Loaded train data. Shape = (26583, 28)
    Some column names had special characters which were removed...
#### Single_Label Multi_Classification problem ####
No test data filename given...
Classifying features using a random sample of 10000 rows from dataset...
#### Single_Label Multi_Classification problem ####
    loading a random sample of 10000 rows into pandas for EDA
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
        6 variable(s) to be removed since ID or low-information variables
    	variables removed = ['icmpcode', 'icmplength', 'icmptype', 'ipflagsmf', 'ipflagsrb', 'ipflagssf']
train data shape before dropping 6 columns = (26583, 28)
	train data shape after dropping columns = (26583, 22)
Removing 6 columns from further processing since ID or low information variables
#######################################################################################
#####  Searching for Uncorrelated List Of Variables (SULOV) in 21 features ############
#######################################################################################
    there are no null values in dataset...
    Removing (1) highly correlated variables:
    ['framelen']
    Following (20) vars selected: ['_wscolTime', 'framenumber', 'ipproto', 'ipttl', 'ipflagsdf', 'ipversion', 'tcpflagsack', 'tcpflagscwr', 'tcpflagsecn', 'tcpflagsfin', 'tcpflagsns', 'tcpflagspush', 'tcpflagsres', 'tcpflagsreset', 'tcpflagssyn', 'tcpflagsurg', 'udplength', 'udpsrcport', 'udpdstport', 'iplen']
Completed SULOV. 20 features selected
Time taken for SULOV method = 0 seconds
Finally 20 vars selected after SULOV
Converting all features to numeric before sending to XGBoost...
Number of booster rounds = 100
        Selected: ['ipflagsdf', 'ipttl', 'tcpflagssyn', 'iplen', 'framenumber']
            Time taken for regular XGBoost feature selection = 2 seconds
        Selected: ['ipflagsdf', 'iplen', 'tcpflagssyn', 'udpsrcport', 'tcpflagsack']
            Time taken for regular XGBoost feature selection = 1 seconds
        Selected: ['udplength', 'iplen', 'tcpflagssyn', 'udpdstport', 'udpsrcport']
            Time taken for regular XGBoost feature selection = 1 seconds
        Selected: ['udplength', 'iplen', 'tcpflagssyn', 'udpdstport', 'udpsrcport']
            Time taken for regular XGBoost feature selection = 1 seconds
        Selected: ['udplength', 'iplen', 'udpdstport', 'udpsrcport']
            Time taken for regular XGBoost feature selection = 1 seconds
    Completed XGBoost feature selection in 1 seconds
Selected 9 important features:
['ipflagsdf', 'ipttl', 'tcpflagssyn', 'iplen', 'framenumber', 'udpsrcport', 'tcpflagsack', 'udplength', 'udpdstport']
Total Time taken for featurewiz selection = 5 seconds
Output contains a list of 9 important features and a train dataframe
    Time taken to create entire pipeline = 5 second(s)

['ip.flags.df',
 'ip.ttl',
 'tcp.flags.syn',
 'ip.len',
 'frame.number',
 'udp.srcport',
 'tcp.flags.ack',
 'udp.length',
 'udp.dstport']

# Novelty detection

In [17]:
detection_results = {}

In [18]:
X_train = df[inlier_rows][fwiz.features]
y_train = df[inlier_rows][target].copy()
y_train.loc[:] = 'Known'

X_test = df[outlier_rows][fwiz.features]
y_test = df[outlier_rows][target].copy()
y_test.loc[:] = 'Unknown'

In [19]:
def accuracy_count_score(y_pred):
    n_outliers = len([y for y in y_pred if y == -1])
    n_inliers = len([y for y in y_pred if y == +1])
    accuracy = n_outliers / (n_outliers + n_inliers)
    return accuracy

#### Elliptic Envelope

In [20]:
def objective(trial):
    try:
        trial.set_user_attr('detector', EllipticEnvelope.__name__)
        assume_centered = trial.suggest_categorical('assume_centered', [True, False])
        support_fraction = trial.suggest_float('support_fraction', 0.0, 1.0)
        clf = EllipticEnvelope(assume_centered=assume_centered, support_fraction=support_fraction, random_state=CFG_SEED)
        clf.fit(X_train)
        y_pred = clf.predict(X_test)
        score = accuracy_count_score(y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['detector']
detection_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:42:19,567] A new study created in memory with name: no-name-9700e9a7-adf1-4da0-bd4a-3ac24fa9009c
[I 2023-06-10 18:42:21,522] Trial 1 finished with value: 0.04680851063829787 and parameters: {'assume_centered': True, 'support_fraction': 0.4263603723952528}. Best is trial 1 with value: 0.04680851063829787.
[I 2023-06-10 18:42:22,026] Trial 0 finished with value: 0.06808510638297872 and parameters: {'assume_centered': True, 'support_fraction': 0.6527219828242414}. Best is trial 0 with value: 0.06808510638297872.
[I 2023-06-10 18:42:23,534] Trial 2 finished with value: 0.0 and parameters: {'assume_centered': False, 'support_fraction': 0.4184258390442406}. Best is trial 0 with value: 0.06808510638297872.
[I 2023-06-10 18:42:23,761] Trial 3 finished with value: 0.04680851063829787 and parameters: {'assume_centered': True, 'support_fraction': 0.17195361223791894}. Best is trial 0 with value: 0.06808510638297872.
[I 2023-06-10 18:42:25,657] Trial 5 finished with value: 0.0 and parameters: {'assume_centered': False, 'support_fraction': 0.5372295159895489}. Best is trial 0 with value: 0.06808510638297872.
[I 2023-06-10 18:42:26,166] Trial 4 finished with value: 0.04680851063829787 and parameters: {'assume_centered': False, 'support_fraction': 0.7404822508876747}. Best is trial 0 with value: 0.06808510638297872.
[I 2023-06-10 18:42:28,231] Trial 7 finished with value: 0.07234042553191489 and parameters: {'assume_centered': True, 'support_fraction': 0.679194308952351}. Best is trial 7 with value: 0.07234042553191489.
[I 2023-06-10 18:42:29,100] Trial 6 finished with value: 0.8808510638297873 and parameters: {'assume_centered': True, 'support_fraction': 0.8393145869648847}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:30,721] Trial 8 finished with value: 0.11914893617021277 and parameters: {'assume_centered': True, 'support_fraction': 0.7723592198993705}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:31,857] Trial 9 finished with value: 0.10212765957446808 and parameters: {'assume_centered': True, 'support_fraction': 0.774425737777747}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:32,428] Trial 10 finished with value: 0.09787234042553192 and parameters: {'assume_centered': True, 'support_fraction': 0.3660192206221715}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:35,996] Trial 12 finished with value: 0.08085106382978724 and parameters: {'assume_centered': True, 'support_fraction': 0.9722509055455328}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:37,359] Trial 11 finished with value: 0.08085106382978724 and parameters: {'assume_centered': True, 'support_fraction': 0.9849934698624218}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:39,991] Trial 13 finished with value: 0.07659574468085106 and parameters: {'assume_centered': True, 'support_fraction': 0.9446070996301849}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:40,858] Trial 14 finished with value: 0.07234042553191489 and parameters: {'assume_centered': True, 'support_fraction': 0.8482442109474244}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:42,515] Trial 15 finished with value: 0.10212765957446808 and parameters: {'assume_centered': True, 'support_fraction': 0.8007290009263661}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:44,285] Trial 17 finished with value: 0.0 and parameters: {'assume_centered': False, 'support_fraction': 0.60625484653594}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:44,387] Trial 16 finished with value: 0.8127659574468085 and parameters: {'assume_centered': False, 'support_fraction': 0.8363914763618083}. Best is trial 6 with value: 0.8808510638297873.
[I 2023-06-10 18:42:48,216] Trial 18 finished with value: 0.9276595744680851 and parameters: {'assume_centered': True, 'support_fraction': 0.8589980006391338}. Best is trial 18 with value: 0.9276595744680851.
[I 2023-06-10 18:42:48,985] Trial 19 finished with value: 0.9063829787234042 and parameters: {'assume_centered': False, 'support_fraction': 0.8674342777686012}. Best is trial 18 with value: 0.9276595744680851.

Best trial: {'assume_centered': True, 'support_fraction': 0.8589980006391338} => 0.928

#### Isolation Forest

In [21]:
def objective(trial):
    try:
        trial.set_user_attr('detector', IsolationForest.__name__)
        n_estimators = trial.suggest_int('n_estimators', 1, 1024, log=True)
        max_samples = trial.suggest_float('max_samples', 0.1, 1.0, step=0.1)
        max_features = trial.suggest_float('max_features', 0.1, 1.0, step=0.1)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])
        clf = IsolationForest(n_estimators=n_estimators, max_samples=max_samples,
                              max_features=max_features, bootstrap=bootstrap,
                              n_jobs=CFG_N_JOBS, random_state=CFG_SEED)
        clf.fit(X_train)
        y_pred = clf.predict(X_test)
        score = accuracy_count_score(y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['detector']
detection_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:42:49,004] A new study created in memory with name: no-name-a17088e2-fa2d-4659-86b7-bc9e18f5a3c8
[I 2023-06-10 18:42:49,016] Trial 1 finished with value: 0.9361702127659575 and parameters: {'n_estimators': 1, 'max_samples': 0.4, 'max_features': 0.30000000000000004, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,045] Trial 2 finished with value: 0.5531914893617021 and parameters: {'n_estimators': 5, 'max_samples': 1.0, 'max_features': 0.2, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,276] Trial 3 finished with value: 0.9063829787234042 and parameters: {'n_estimators': 97, 'max_samples': 0.1, 'max_features': 0.30000000000000004, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,287] Trial 4 finished with value: 0.2127659574468085 and parameters: {'n_estimators': 1, 'max_samples': 0.1, 'max_features': 1.0, 'bootstrap': False}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,313] Trial 5 finished with value: 0.9319148936170213 and parameters: {'n_estimators': 3, 'max_samples': 1.0, 'max_features': 0.9, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,347] Trial 6 finished with value: 0.625531914893617 and parameters: {'n_estimators': 10, 'max_samples': 0.1, 'max_features': 0.1, 'bootstrap': False}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,392] Trial 7 finished with value: 0.9319148936170213 and parameters: {'n_estimators': 11, 'max_samples': 0.2, 'max_features': 0.6, 'bootstrap': False}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,434] Trial 8 finished with value: 0.33617021276595743 and parameters: {'n_estimators': 5, 'max_samples': 0.9, 'max_features': 0.30000000000000004, 'bootstrap': False}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,524] Trial 9 finished with value: 0.8723404255319149 and parameters: {'n_estimators': 17, 'max_samples': 1.0, 'max_features': 0.6, 'bootstrap': False}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,538] Trial 10 finished with value: 0.8468085106382979 and parameters: {'n_estimators': 3, 'max_samples': 0.1, 'max_features': 0.1, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,770] Trial 0 finished with value: 0.9191489361702128 and parameters: {'n_estimators': 191, 'max_samples': 1.0, 'max_features': 0.4, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,791] Trial 12 finished with value: 0.20851063829787234 and parameters: {'n_estimators': 1, 'max_samples': 0.5, 'max_features': 0.9, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,813] Trial 13 finished with value: 0.9361702127659575 and parameters: {'n_estimators': 1, 'max_samples': 0.5, 'max_features': 0.8, 'bootstrap': True}. Best is trial 1 with value: 0.9361702127659575.
[I 2023-06-10 18:42:49,833] Trial 14 finished with value: 0.9659574468085106 and parameters: {'n_estimators': 1, 'max_samples': 0.5, 'max_features': 0.7000000000000001, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:50,020] Trial 15 finished with value: 0.9319148936170213 and parameters: {'n_estimators': 46, 'max_samples': 0.7000000000000001, 'max_features': 0.5, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:51,607] Trial 16 finished with value: 0.9276595744680851 and parameters: {'n_estimators': 507, 'max_samples': 0.30000000000000004, 'max_features': 0.7000000000000001, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:51,627] Trial 17 finished with value: 0.9361702127659575 and parameters: {'n_estimators': 1, 'max_samples': 0.4, 'max_features': 0.5, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:51,650] Trial 18 finished with value: 0.9361702127659575 and parameters: {'n_estimators': 2, 'max_samples': 0.7000000000000001, 'max_features': 0.7000000000000001, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:51,678] Trial 19 finished with value: 0.3276595744680851 and parameters: {'n_estimators': 2, 'max_samples': 0.7000000000000001, 'max_features': 0.4, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.
[I 2023-06-10 18:42:51,887] Trial 11 finished with value: 0.9191489361702128 and parameters: {'n_estimators': 810, 'max_samples': 0.5, 'max_features': 0.4, 'bootstrap': True}. Best is trial 14 with value: 0.9659574468085106.

Best trial: {'n_estimators': 1, 'max_samples': 0.5, 'max_features': 0.7000000000000001, 'bootstrap': True} => 0.966

#### Local Outlier Factor

In [22]:
def objective(trial):
    try:
        trial.set_user_attr('detector', LocalOutlierFactor.__name__)
        n_neighbors = trial.suggest_int('n_neighbors', 1, 4096, log=True)
        algorithm = trial.suggest_categorical('algorithm', ['ball_tree', 'kd_tree', 'brute'])
        leaf_size = trial.suggest_int('leaf_size', 1, 4096, log=True)
        clf = LocalOutlierFactor(n_neighbors=n_neighbors, algorithm=algorithm, 
                                 leaf_size=leaf_size, novelty=True, n_jobs=CFG_N_JOBS)
        clf.fit(X_train)
        y_pred = clf.predict(X_test)
        score = accuracy_count_score(y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['detector']
completed_trials = filter_completed_trials(study.trials)
detection_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:42:51,898] A new study created in memory with name: no-name-b710573d-4beb-4b54-92c3-e567766cc4d2
[I 2023-06-10 18:42:53,483] Trial 1 finished with value: 0.0 and parameters: {'n_neighbors': 627, 'algorithm': 'ball_tree', 'leaf_size': 127}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:02,138] Trial 2 finished with value: 0.0 and parameters: {'n_neighbors': 2815, 'algorithm': 'kd_tree', 'leaf_size': 2956}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:10,267] Trial 3 finished with value: 0.0 and parameters: {'n_neighbors': 2616, 'algorithm': 'kd_tree', 'leaf_size': 6}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:10,874] Trial 4 finished with value: 0.0 and parameters: {'n_neighbors': 25, 'algorithm': 'ball_tree', 'leaf_size': 1256}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:11,131] Trial 0 finished with value: 0.0 and parameters: {'n_neighbors': 167, 'algorithm': 'brute', 'leaf_size': 3796}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:11,401] Trial 6 finished with value: 0.0 and parameters: {'n_neighbors': 111, 'algorithm': 'kd_tree', 'leaf_size': 16}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:11,802] Trial 7 finished with value: 0.6085106382978723 and parameters: {'n_neighbors': 1, 'algorithm': 'ball_tree', 'leaf_size': 985}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:17,966] Trial 5 finished with value: 0.0 and parameters: {'n_neighbors': 2630, 'algorithm': 'ball_tree', 'leaf_size': 15}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:18,639] Trial 9 finished with value: 0.0 and parameters: {'n_neighbors': 187, 'algorithm': 'kd_tree', 'leaf_size': 469}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:18,871] Trial 10 finished with value: 0.37872340425531914 and parameters: {'n_neighbors': 3, 'algorithm': 'ball_tree', 'leaf_size': 334}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,322] Trial 8 finished with value: 0.0 and parameters: {'n_neighbors': 81, 'algorithm': 'brute', 'leaf_size': 6}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,412] Trial 12 finished with value: 0.6085106382978723 and parameters: {'n_neighbors': 1, 'algorithm': 'ball_tree', 'leaf_size': 203}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,483] Trial 13 finished with value: 0.6085106382978723 and parameters: {'n_neighbors': 1, 'algorithm': 'ball_tree', 'leaf_size': 95}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,796] Trial 14 finished with value: 0.6085106382978723 and parameters: {'n_neighbors': 1, 'algorithm': 'ball_tree', 'leaf_size': 532}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,901] Trial 15 finished with value: 0.11063829787234042 and parameters: {'n_neighbors': 6, 'algorithm': 'ball_tree', 'leaf_size': 1}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:28,926] Trial 11 finished with value: 0.6085106382978723 and parameters: {'n_neighbors': 1, 'algorithm': 'brute', 'leaf_size': 1}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:29,116] Trial 16 finished with value: 0.11063829787234042 and parameters: {'n_neighbors': 6, 'algorithm': 'ball_tree', 'leaf_size': 199}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:43,923] Trial 17 finished with value: 0.11063829787234042 and parameters: {'n_neighbors': 6, 'algorithm': 'brute', 'leaf_size': 1}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:43,935] Trial 18 finished with value: 0.00851063829787234 and parameters: {'n_neighbors': 21, 'algorithm': 'brute', 'leaf_size': 68}. Best is trial 7 with value: 0.6085106382978723.
[I 2023-06-10 18:43:55,759] Trial 19 finished with value: 0.02553191489361702 and parameters: {'n_neighbors': 17, 'algorithm': 'brute', 'leaf_size': 63}. Best is trial 7 with value: 0.6085106382978723.

Best trial: {'n_neighbors': 1, 'algorithm': 'ball_tree', 'leaf_size': 985} => 0.609

#### One Class SVM (SGD)

In [23]:
def objective(trial):
    try:
        trial.set_user_attr('detector', SGDOneClassSVM.__name__)
        gamma = trial.suggest_float('kernel_gamma', 0.05, 1, step=0.05)
        n_components = trial.suggest_int('kernel_n_components', 50, 150, step=5)
        nu = trial.suggest_float('sgd_nu', 0.05, 1, step=0.05)
        clf = make_pipeline(
            Nystroem(gamma=gamma, n_components=n_components, random_state=CFG_SEED),
            SGDOneClassSVM(nu=nu, random_state=CFG_SEED)
        )
        clf.fit(X_train)
        y_pred = clf.predict(X_test)
        score = accuracy_count_score(y_pred)
        return score
    except:
        return optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['detector']
completed_trials = filter_completed_trials(study.trials)
detection_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:43:55,783] A new study created in memory with name: no-name-ca8abe2e-dec8-43c8-98e6-0a0eed1ca023
[I 2023-06-10 18:43:55,969] Trial 1 finished with value: 0.0 and parameters: {'kernel_gamma': 0.4, 'kernel_n_components': 95, 'sgd_nu': 0.15000000000000002}. Best is trial 1 with value: 0.0.
[I 2023-06-10 18:43:56,006] Trial 0 finished with value: 1.0 and parameters: {'kernel_gamma': 0.8, 'kernel_n_components': 105, 'sgd_nu': 0.9500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,096] Trial 3 finished with value: 0.0 and parameters: {'kernel_gamma': 0.9500000000000001, 'kernel_n_components': 50, 'sgd_nu': 0.35000000000000003}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,097] Trial 2 finished with value: 0.0 and parameters: {'kernel_gamma': 0.8, 'kernel_n_components': 70, 'sgd_nu': 0.1}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,324] Trial 4 finished with value: 0.0 and parameters: {'kernel_gamma': 0.35000000000000003, 'kernel_n_components': 115, 'sgd_nu': 0.2}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,361] Trial 5 finished with value: 0.0 and parameters: {'kernel_gamma': 0.55, 'kernel_n_components': 130, 'sgd_nu': 0.55}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,602] Trial 6 finished with value: 1.0 and parameters: {'kernel_gamma': 0.15000000000000002, 'kernel_n_components': 150, 'sgd_nu': 0.7500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,614] Trial 7 finished with value: 0.0 and parameters: {'kernel_gamma': 1.0, 'kernel_n_components': 140, 'sgd_nu': 0.6500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,771] Trial 8 finished with value: 1.0 and parameters: {'kernel_gamma': 0.7000000000000001, 'kernel_n_components': 85, 'sgd_nu': 0.9500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:56,772] Trial 9 finished with value: 0.0 and parameters: {'kernel_gamma': 0.8500000000000001, 'kernel_n_components': 90, 'sgd_nu': 0.1}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,015] Trial 10 finished with value: 1.0 and parameters: {'kernel_gamma': 0.6500000000000001, 'kernel_n_components': 115, 'sgd_nu': 1.0}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,031] Trial 11 finished with value: 1.0 and parameters: {'kernel_gamma': 0.6000000000000001, 'kernel_n_components': 120, 'sgd_nu': 1.0}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,341] Trial 12 finished with value: 1.0 and parameters: {'kernel_gamma': 0.05, 'kernel_n_components': 150, 'sgd_nu': 0.8}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,346] Trial 13 finished with value: 1.0 and parameters: {'kernel_gamma': 0.05, 'kernel_n_components': 150, 'sgd_nu': 0.7500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,491] Trial 15 finished with value: 1.0 and parameters: {'kernel_gamma': 0.25, 'kernel_n_components': 70, 'sgd_nu': 0.8500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,629] Trial 14 finished with value: 1.0 and parameters: {'kernel_gamma': 0.05, 'kernel_n_components': 150, 'sgd_nu': 0.8500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,692] Trial 16 finished with value: 0.0 and parameters: {'kernel_gamma': 0.3, 'kernel_n_components': 105, 'sgd_nu': 0.6000000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,825] Trial 17 finished with value: 0.0 and parameters: {'kernel_gamma': 0.2, 'kernel_n_components': 105, 'sgd_nu': 0.6500000000000001}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:57,928] Trial 18 finished with value: 1.0 and parameters: {'kernel_gamma': 0.5, 'kernel_n_components': 130, 'sgd_nu': 0.4}. Best is trial 0 with value: 1.0.
[I 2023-06-10 18:43:58,057] Trial 19 finished with value: 0.0 and parameters: {'kernel_gamma': 0.45, 'kernel_n_components': 130, 'sgd_nu': 0.45}. Best is trial 0 with value: 1.0.

Best trial: {'kernel_gamma': 0.8, 'kernel_n_components': 105, 'sgd_nu': 0.9500000000000001} => 1.000

#### Summarize results

In [24]:
pd.DataFrame.from_dict(detection_results).round(3)

,EllipticEnvelope,IsolationForest,LocalOutlierFactor,SGDOneClassSVM
score_min,0.000,0.209,0.000,0.000
score_max,0.928,0.966,0.609,1.000
score_mean,0.227,0.758,0.189,0.500
score_std,0.330,0.265,0.256,0.500
time_min,1.705,0.008,0.071,0.088
time_max,1.705,0.008,0.071,0.088
time_mean,2.902,0.276,5.793,0.218
time_std,1.036,0.599,6.527,0.060

# Classification

In [25]:
classification_results = {}

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X[fwiz.features], y, test_size=0.2, random_state=CFG_SEED)

print('\nTrain data before resampling:', X_train.shape, y_train.shape, '\n')
pretty_print_value_counts(y_train)

X_train, y_train = SMOTETomek(n_jobs=CFG_N_JOBS, random_state=CFG_SEED).fit_resample(X_train, y_train)

print('\nTrain data after resampling:', X_train.shape, y_train.shape, '\n')
pretty_print_value_counts(y_train)

Train data before resampling: (21266, 9) (21266,)

       counts      %
label
0       11508  54.1%
1        8217  38.6%
2         795   3.7%
3         557   2.6%
4         189   0.9%

Train data after resampling: (54694, 9) (54694,)

       counts      %
label
4       11345  20.7%
3       11106  20.3%
1       11100  20.3%
2       10754  19.7%
0       10389  19.0%

#### Decision Tree

In [27]:
def objective(trial):
    try:
        trial.set_user_attr('classifier', DecisionTreeClassifier.__name__)
        max_depth = trial.suggest_int('max_depth', 2, 10)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        max_features = trial.suggest_categorical('max_features', ['auto', 'sqrt', 'log2', None])
        criterion = trial.suggest_categorical('criterion', ['gini', 'entropy'])
        clf = DecisionTreeClassifier(
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            max_features=max_features,
            criterion=criterion,
            random_state=CFG_SEED
        )
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        score = accuracy_score(y_test, y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['classifier']
classification_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:43:58,357] A new study created in memory with name: no-name-95aa9c15-0dce-4541-ab0d-bb735bd9957a
[I 2023-06-10 18:43:58,380] Trial 0 finished with value: 0.7380101561030656 and parameters: {'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 0 with value: 0.7380101561030656.
[I 2023-06-10 18:43:58,393] Trial 1 finished with value: 0.9053977807034042 and parameters: {'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'entropy'}. Best is trial 1 with value: 0.9053977807034042.
[I 2023-06-10 18:43:58,406] Trial 2 finished with value: 0.9116042881324055 and parameters: {'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,425] Trial 3 finished with value: 0.8931728418280985 and parameters: {'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,453] Trial 5 finished with value: 0.862704532631183 and parameters: {'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,472] Trial 4 finished with value: 0.8875305623471883 and parameters: {'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': None, 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,486] Trial 6 finished with value: 0.8717321798006394 and parameters: {'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'auto', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,507] Trial 7 finished with value: 0.8965582095166448 and parameters: {'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'auto', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,518] Trial 8 finished with value: 0.8884709422606734 and parameters: {'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'auto', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,535] Trial 9 finished with value: 0.9097235283054353 and parameters: {'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,563] Trial 10 finished with value: 0.8508557457212714 and parameters: {'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,577] Trial 11 finished with value: 0.7350009403799135 and parameters: {'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,605] Trial 12 finished with value: 0.8984389693436148 and parameters: {'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,639] Trial 13 finished with value: 0.8538649614444236 and parameters: {'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,661] Trial 14 finished with value: 0.8538649614444236 and parameters: {'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,674] Trial 15 finished with value: 0.40455143878126765 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,697] Trial 16 finished with value: 0.40455143878126765 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,716] Trial 17 finished with value: 0.9099116042881324 and parameters: {'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,739] Trial 18 finished with value: 0.8879067143125823 and parameters: {'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'criterion': 'gini'}. Best is trial 2 with value: 0.9116042881324055.
[I 2023-06-10 18:43:58,749] Trial 19 finished with value: 0.7350009403799135 and parameters: {'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'criterion': 'entropy'}. Best is trial 2 with value: 0.9116042881324055.

Best trial: {'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'entropy'} => 0.912

#### LightGBM

In [28]:
def objective(trial):
    try:
        trial.set_user_attr('classifier', LGBMClassifier.__name__)
        learning_rate = trial.suggest_float('learning_rate', 0.1, 1.0, step=0.05)
        n_estimators = trial.suggest_int('n_estimators', 1, 200)
        max_depth = trial.suggest_int('max_depth', 3, 10)
        num_leaves = trial.suggest_int('num_leaves', 10, 100)
        min_child_samples = trial.suggest_int('min_child_samples', 1, 20)
        subsample = trial.suggest_float('subsample', 0.5, 1.0, step=0.1)
        colsample_bytree = trial.suggest_float('colsample_bytree', 0.5, 1.0, step=0.1)
        reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0, step=0.1)
        clf = LGBMClassifier(
            learning_rate=learning_rate,
            n_estimators=n_estimators,
            max_depth=max_depth,
            num_leaves=num_leaves,
            min_child_samples=min_child_samples,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            reg_alpha=reg_alpha,
            random_state=CFG_SEED
        )
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        score = accuracy_score(y_test, y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['classifier']
classification_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:43:58,763] A new study created in memory with name: no-name-3cd393bb-7558-4f4a-be1e-c217b8ec6143
[I 2023-06-10 18:43:59,167] Trial 0 finished with value: 0.939439533571563 and parameters: {'learning_rate': 0.15000000000000002, 'n_estimators': 40, 'max_depth': 6, 'num_leaves': 87, 'min_child_samples': 1, 'subsample': 0.7, 'colsample_bytree': 0.6, 'reg_alpha': 0.4}. Best is trial 0 with value: 0.939439533571563.
[I 2023-06-10 18:43:59,301] Trial 1 finished with value: 0.7131841263870604 and parameters: {'learning_rate': 0.75, 'n_estimators': 157, 'max_depth': 4, 'num_leaves': 78, 'min_child_samples': 16, 'subsample': 0.8, 'colsample_bytree': 1.0, 'reg_alpha': 0.4}. Best is trial 0 with value: 0.939439533571563.
[I 2023-06-10 18:43:59,665] Trial 3 finished with value: 0.941696445363927 and parameters: {'learning_rate': 0.30000000000000004, 'n_estimators': 103, 'max_depth': 3, 'num_leaves': 54, 'min_child_samples': 18, 'subsample': 0.7, 'colsample_bytree': 0.6, 'reg_alpha': 0.7000000000000001}. Best is trial 3 with value: 0.941696445363927.
[I 2023-06-10 18:43:59,806] Trial 2 finished with value: 0.7402670678954297 and parameters: {'learning_rate': 0.8, 'n_estimators': 127, 'max_depth': 10, 'num_leaves': 52, 'min_child_samples': 19, 'subsample': 0.7, 'colsample_bytree': 0.6, 'reg_alpha': 0.0}. Best is trial 3 with value: 0.941696445363927.
[I 2023-06-10 18:44:00,540] Trial 4 finished with value: 0.9488433327064134 and parameters: {'learning_rate': 0.2, 'n_estimators': 128, 'max_depth': 9, 'num_leaves': 29, 'min_child_samples': 16, 'subsample': 0.7, 'colsample_bytree': 0.5, 'reg_alpha': 0.30000000000000004}. Best is trial 4 with value: 0.9488433327064134.
[I 2023-06-10 18:44:00,727] Trial 5 finished with value: 0.9507240925333835 and parameters: {'learning_rate': 0.45000000000000007, 'n_estimators': 157, 'max_depth': 8, 'num_leaves': 49, 'min_child_samples': 15, 'subsample': 0.5, 'colsample_bytree': 0.5, 'reg_alpha': 0.5}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:00,917] Trial 6 finished with value: 0.941320293398533 and parameters: {'learning_rate': 0.1, 'n_estimators': 80, 'max_depth': 5, 'num_leaves': 92, 'min_child_samples': 1, 'subsample': 0.9, 'colsample_bytree': 1.0, 'reg_alpha': 0.8}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:01,478] Trial 7 finished with value: 0.9488433327064134 and parameters: {'learning_rate': 0.2, 'n_estimators': 104, 'max_depth': 9, 'num_leaves': 37, 'min_child_samples': 2, 'subsample': 1.0, 'colsample_bytree': 0.5, 'reg_alpha': 0.6000000000000001}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:01,887] Trial 9 finished with value: 0.942260673312018 and parameters: {'learning_rate': 0.1, 'n_estimators': 89, 'max_depth': 5, 'num_leaves': 80, 'min_child_samples': 2, 'subsample': 0.6, 'colsample_bytree': 0.9, 'reg_alpha': 0.30000000000000004}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:01,985] Trial 10 finished with value: 0.9349257099868347 and parameters: {'learning_rate': 0.25, 'n_estimators': 17, 'max_depth': 10, 'num_leaves': 14, 'min_child_samples': 4, 'subsample': 1.0, 'colsample_bytree': 1.0, 'reg_alpha': 0.6000000000000001}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:02,085] Trial 8 finished with value: 0.9494075606545044 and parameters: {'learning_rate': 0.4, 'n_estimators': 164, 'max_depth': 9, 'num_leaves': 68, 'min_child_samples': 17, 'subsample': 0.7, 'colsample_bytree': 0.6, 'reg_alpha': 0.2}. Best is trial 5 with value: 0.9507240925333835.
[I 2023-06-10 18:44:03,013] Trial 11 finished with value: 0.9526048523603536 and parameters: {'learning_rate': 0.5, 'n_estimators': 198, 'max_depth': 7, 'num_leaves': 68, 'min_child_samples': 10, 'subsample': 0.5, 'colsample_bytree': 0.8, 'reg_alpha': 0.9}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:03,335] Trial 12 finished with value: 0.9492194846718074 and parameters: {'learning_rate': 0.5, 'n_estimators': 194, 'max_depth': 8, 'num_leaves': 64, 'min_child_samples': 12, 'subsample': 0.5, 'colsample_bytree': 0.7, 'reg_alpha': 0.1}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:04,041] Trial 13 finished with value: 0.9516644724468686 and parameters: {'learning_rate': 0.55, 'n_estimators': 196, 'max_depth': 7, 'num_leaves': 65, 'min_child_samples': 10, 'subsample': 0.5, 'colsample_bytree': 0.8, 'reg_alpha': 1.0}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:04,108] Trial 14 finished with value: 0.2510814369005078 and parameters: {'learning_rate': 0.65, 'n_estimators': 198, 'max_depth': 7, 'num_leaves': 42, 'min_child_samples': 9, 'subsample': 0.5, 'colsample_bytree': 0.8, 'reg_alpha': 0.9}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:04,730] Trial 16 finished with value: 0.5950724092533384 and parameters: {'learning_rate': 1.0, 'n_estimators': 179, 'max_depth': 7, 'num_leaves': 68, 'min_child_samples': 9, 'subsample': 0.6, 'colsample_bytree': 0.8, 'reg_alpha': 1.0}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:05,109] Trial 15 finished with value: 0.9518525484295656 and parameters: {'learning_rate': 0.65, 'n_estimators': 191, 'max_depth': 7, 'num_leaves': 100, 'min_child_samples': 8, 'subsample': 0.5, 'colsample_bytree': 0.8, 'reg_alpha': 1.0}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:05,338] Trial 17 finished with value: 0.37728042129020123 and parameters: {'learning_rate': 0.65, 'n_estimators': 133, 'max_depth': 6, 'num_leaves': 100, 'min_child_samples': 12, 'subsample': 0.6, 'colsample_bytree': 0.9, 'reg_alpha': 1.0}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:05,684] Trial 19 finished with value: 0.5029151777318036 and parameters: {'learning_rate': 0.9500000000000001, 'n_estimators': 65, 'max_depth': 5, 'num_leaves': 100, 'min_child_samples': 6, 'subsample': 0.6, 'colsample_bytree': 0.7, 'reg_alpha': 0.8}. Best is trial 11 with value: 0.9526048523603536.
[I 2023-06-10 18:44:05,747] Trial 18 finished with value: 0.36411510250141055 and parameters: {'learning_rate': 0.65, 'n_estimators': 136, 'max_depth': 6, 'num_leaves': 100, 'min_child_samples': 6, 'subsample': 0.6, 'colsample_bytree': 0.9, 'reg_alpha': 0.8}. Best is trial 11 with value: 0.9526048523603536.

Best trial: {'learning_rate': 0.5, 'n_estimators': 198, 'max_depth': 7, 'num_leaves': 68, 'min_child_samples': 10, 'subsample': 0.5, 'colsample_bytree': 0.8, 'reg_alpha': 0.9} => 0.953

#### Random Forest

In [29]:
def objective(trial):
    try:
        trial.set_user_attr('classifier', RandomForestClassifier.__name__)
        n_estimators = trial.suggest_int('n_estimators', 100, 1000, step=100)
        max_depth = trial.suggest_int('max_depth', 3, 10)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        clf = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=CFG_SEED
        )
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        score = accuracy_score(y_test, y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['classifier']
classification_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:44:05,763] A new study created in memory with name: no-name-743284e8-6056-46a3-9ce1-1552c16bdeda
[I 2023-06-10 18:44:07,850] Trial 0 finished with value: 0.9311641903328944 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:11,787] Trial 1 finished with value: 0.9300357344367124 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:13,604] Trial 3 finished with value: 0.9195034794056799 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:20,119] Trial 2 finished with value: 0.8732367876622156 and parameters: {'n_estimators': 800, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:20,748] Trial 4 finished with value: 0.9179988715441039 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:21,360] Trial 5 finished with value: 0.6798946774496897 and parameters: {'n_estimators': 100, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:28,242] Trial 6 finished with value: 0.9232649990596201 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:28,970] Trial 7 finished with value: 0.9242053789731052 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:34,054] Trial 9 finished with value: 0.8920443859319165 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:46,448] Trial 8 finished with value: 0.9307880383675005 and parameters: {'n_estimators': 900, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:44:47,504] Trial 10 finished with value: 0.9005078051532819 and parameters: {'n_estimators': 800, 'max_depth': 6, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.9311641903328944.
[I 2023-06-10 18:45:01,202] Trial 11 finished with value: 0.9334211021252586 and parameters: {'n_estimators': 700, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.9334211021252586.
[I 2023-06-10 18:45:08,588] Trial 12 finished with value: 0.9341734060560466 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:45:14,106] Trial 13 finished with value: 0.9336091781079556 and parameters: {'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:45:29,675] Trial 14 finished with value: 0.9341734060560466 and parameters: {'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:45:34,390] Trial 15 finished with value: 0.9322926462290766 and parameters: {'n_estimators': 1000, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:45:47,706] Trial 17 finished with value: 0.8162497649050217 and parameters: {'n_estimators': 1000, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:45:49,900] Trial 16 finished with value: 0.9307880383675005 and parameters: {'n_estimators': 1000, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:46:04,285] Trial 19 finished with value: 0.922700771111529 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.9341734060560466.
[I 2023-06-10 18:46:05,412] Trial 18 finished with value: 0.9304118864021065 and parameters: {'n_estimators': 900, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.9341734060560466.

Best trial: {'n_estimators': 1000, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1} => 0.934

#### XGBoost

In [30]:
def objective(trial):
    try:
        trial.set_user_attr('classifier', XGBClassifier.__name__)
        eta = trial.suggest_float('eta', 0.01, 0.3, step=0.01)
        max_depth = trial.suggest_int('max_depth', 3, 10)
        subsample = trial.suggest_float('subsample', 0.5, 1.0, step=0.1)
        colsample_bytree = trial.suggest_float('colsample_bytree', 0.5, 1.0, step=0.1)
        min_child_weight = trial.suggest_int('min_child_weight', 1, 10)
        gamma = trial.suggest_float('gamma', 0.0, 1.0, step=0.1)
        reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0, step=0.1)
        reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0, step=0.1)
        clf = XGBClassifier(
            objective='binary:logistic',
            eval_metric='logloss',
            eta=eta,
            max_depth=max_depth,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            min_child_weight=min_child_weight,
            gamma=gamma,
            reg_lambda=reg_lambda,
            reg_alpha=reg_alpha,
            n_jobs=CFG_N_JOBS,
            random_state=CFG_SEED
        )
        clf.fit(X_train, y_train)
        y_pred = clf.predict(X_test)
        score = accuracy_score(y_test, y_pred)
        return score
    except:
        raise optuna.TrialPruned()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=CFG_N_TRIALS, n_jobs=CFG_N_JOBS)
print(f'Best trial: {study.best_trial.params} => {study.best_trial.values[0]:.3f}')

clf_name = study.best_trial.user_attrs['classifier']
classification_results[clf_name] = get_results_statistics(study)

[I 2023-06-10 18:46:05,425] A new study created in memory with name: no-name-15cba43d-7959-47ea-981e-4efed1b276e7
[I 2023-06-10 18:46:10,858] Trial 1 finished with value: 0.9347376340041377 and parameters: {'eta': 0.06999999999999999, 'max_depth': 6, 'subsample': 0.6, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.5, 'reg_lambda': 0.9, 'reg_alpha': 0.6000000000000001}. Best is trial 1 with value: 0.9347376340041377.
[I 2023-06-10 18:46:11,230] Trial 0 finished with value: 0.9505360165506864 and parameters: {'eta': 0.27, 'max_depth': 8, 'subsample': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'gamma': 0.0, 'reg_lambda': 0.2, 'reg_alpha': 1.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:15,244] Trial 3 finished with value: 0.942260673312018 and parameters: {'eta': 0.2, 'max_depth': 4, 'subsample': 0.7, 'colsample_bytree': 0.8, 'min_child_weight': 7, 'gamma': 0.6000000000000001, 'reg_lambda': 0.6000000000000001, 'reg_alpha': 0.30000000000000004}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:16,109] Trial 2 finished with value: 0.9257099868346812 and parameters: {'eta': 0.03, 'max_depth': 6, 'subsample': 0.5, 'colsample_bytree': 0.6, 'min_child_weight': 9, 'gamma': 0.7000000000000001, 'reg_lambda': 0.6000000000000001, 'reg_alpha': 0.1}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:20,323] Trial 4 finished with value: 0.9505360165506864 and parameters: {'eta': 0.19, 'max_depth': 7, 'subsample': 1.0, 'colsample_bytree': 0.7, 'min_child_weight': 2, 'gamma': 0.30000000000000004, 'reg_lambda': 0.4, 'reg_alpha': 0.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:21,562] Trial 5 finished with value: 0.9497837126198985 and parameters: {'eta': 0.2, 'max_depth': 7, 'subsample': 1.0, 'colsample_bytree': 0.9, 'min_child_weight': 5, 'gamma': 0.6000000000000001, 'reg_lambda': 0.1, 'reg_alpha': 0.7000000000000001}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:27,362] Trial 6 finished with value: 0.9497837126198985 and parameters: {'eta': 0.24000000000000002, 'max_depth': 8, 'subsample': 0.6, 'colsample_bytree': 1.0, 'min_child_weight': 6, 'gamma': 0.2, 'reg_lambda': 0.6000000000000001, 'reg_alpha': 1.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:28,501] Trial 7 finished with value: 0.9443295091216851 and parameters: {'eta': 0.060000000000000005, 'max_depth': 9, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 6, 'gamma': 0.2, 'reg_lambda': 0.7000000000000001, 'reg_alpha': 0.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:32,809] Trial 8 finished with value: 0.941884521346624 and parameters: {'eta': 0.08, 'max_depth': 7, 'subsample': 0.9, 'colsample_bytree': 0.6, 'min_child_weight': 1, 'gamma': 0.30000000000000004, 'reg_lambda': 0.5, 'reg_alpha': 0.4}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:33,043] Trial 9 finished with value: 0.9089712243746474 and parameters: {'eta': 0.01, 'max_depth': 4, 'subsample': 0.9, 'colsample_bytree': 1.0, 'min_child_weight': 2, 'gamma': 0.1, 'reg_lambda': 0.8, 'reg_alpha': 0.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:35,963] Trial 10 finished with value: 0.9349257099868347 and parameters: {'eta': 0.21000000000000002, 'max_depth': 3, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 2, 'gamma': 0.6000000000000001, 'reg_lambda': 0.5, 'reg_alpha': 0.6000000000000001}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:38,324] Trial 11 finished with value: 0.9477148768102314 and parameters: {'eta': 0.3, 'max_depth': 10, 'subsample': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 4, 'gamma': 0.9, 'reg_lambda': 0.0, 'reg_alpha': 1.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:41,284] Trial 12 finished with value: 0.9477148768102314 and parameters: {'eta': 0.28, 'max_depth': 10, 'subsample': 0.5, 'colsample_bytree': 0.5, 'min_child_weight': 4, 'gamma': 1.0, 'reg_lambda': 0.2, 'reg_alpha': 1.0}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:44,163] Trial 13 finished with value: 0.9484671807410193 and parameters: {'eta': 0.14, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 4, 'gamma': 0.0, 'reg_lambda': 0.30000000000000004, 'reg_alpha': 0.8}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:47,104] Trial 14 finished with value: 0.9499717886025955 and parameters: {'eta': 0.15000000000000002, 'max_depth': 8, 'subsample': 0.8, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'gamma': 0.0, 'reg_lambda': 0.30000000000000004, 'reg_alpha': 0.8}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:50,054] Trial 15 finished with value: 0.9503479405679894 and parameters: {'eta': 0.15000000000000002, 'max_depth': 8, 'subsample': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1, 'gamma': 0.4, 'reg_lambda': 0.30000000000000004, 'reg_alpha': 0.2}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:51,448] Trial 16 finished with value: 0.9486552567237164 and parameters: {'eta': 0.25, 'max_depth': 5, 'subsample': 0.7, 'colsample_bytree': 0.6, 'min_child_weight': 1, 'gamma': 0.4, 'reg_lambda': 0.30000000000000004, 'reg_alpha': 0.2}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:54,429] Trial 17 finished with value: 0.9469625728794433 and parameters: {'eta': 0.26, 'max_depth': 5, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.30000000000000004, 'reg_lambda': 0.4, 'reg_alpha': 0.4}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:46:57,782] Trial 18 finished with value: 0.9497837126198985 and parameters: {'eta': 0.11, 'max_depth': 9, 'subsample': 0.9, 'colsample_bytree': 0.8, 'min_child_weight': 10, 'gamma': 0.2, 'reg_lambda': 0.0, 'reg_alpha': 0.4}. Best is trial 0 with value: 0.9505360165506864.
[I 2023-06-10 18:47:01,309] Trial 19 finished with value: 0.9499717886025955 and parameters: {'eta': 0.11, 'max_depth': 9, 'subsample': 0.6, 'colsample_bytree': 0.9, 'min_child_weight': 8, 'gamma': 0.1, 'reg_lambda': 0.0, 'reg_alpha': 0.5}. Best is trial 0 with value: 0.9505360165506864.

Best trial: {'eta': 0.27, 'max_depth': 8, 'subsample': 0.5, 'colsample_bytree': 0.7, 'min_child_weight': 3, 'gamma': 0.0, 'reg_lambda': 0.2, 'reg_alpha': 1.0} => 0.951

#### Summarize results

In [31]:
pd.DataFrame.from_dict(classification_results).round(3)

,DecisionTreeClassifier,LGBMClassifier,RandomForestClassifier,XGBClassifier
score_min,0.405,0.251,0.680,0.909
score_max,0.912,0.953,0.934,0.951
score_mean,0.815,0.792,0.905,0.944
score_std,0.148,0.233,0.059,0.010
time_min,0.021,0.098,1.239,3.153
time_max,0.021,0.098,1.239,3.153
time_mean,0.037,0.693,11.907,5.410
time_std,0.011,0.307,6.537,0.972